Ensure workflows fail appropriately
I noticed when adding all of the clippy code, that the lint job failed,
and the stable and msrv tests still ran (because of the `always()`
conditional), and then the workflow passed. This logic is all a bit
convoluted, but necessary to save on timing and compute resources.

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -54,7 +54,7 @@ jobs:
     needs:
       - changes
     runs-on: ubuntu-latest
-    if: github.event_name == 'pull_request' && needs.changes.outputs.rust == 'true'
+    if: needs.changes.outputs.rust == 'true'
     steps:
       - name: Checkout source code
         uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
@@ -75,7 +75,7 @@ jobs:
     needs:
       - changes
     runs-on: ubuntu-latest
-    if: github.event_name == 'pull_request' && needs.changes.outputs.rust == 'true'
+    if: needs.changes.outputs.rust == 'true'
     steps:
       - name: Checkout source code
         uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
@@ -94,7 +94,6 @@ jobs:
   test_stable:
     name: test / stable
     needs:
-      - changes
       - format
       - lint
     defaults:
@@ -108,7 +107,6 @@ jobs:
           - ubuntu-latest
           - windows-latest
     runs-on: ${{ matrix.platform }}
-    if: always() && needs.changes.outputs.rust == 'true'
     steps:
       - name: Checkout source code
         uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
@@ -134,11 +132,9 @@ jobs:
   test_msrv:
     name: test / msrv
     needs:
-      - changes
       - format
       - lint
     runs-on: ubuntu-latest
-    if: always() && needs.changes.outputs.rust == 'true'
     steps:
       - name: Checkout source code
         uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
@@ -176,6 +172,8 @@ jobs:
     name: rust workflow ready
     needs:
       - changes
+      - format
+      - lint
       - test_stable
       - test_msrv
     runs-on: ubuntu-latest
@@ -184,6 +182,26 @@ jobs:
       - name: 'Check status of job_id: changes'
         run: |-
           RESULT="${{ needs.changes.result }}";
+          if [[ $RESULT == "success" || $RESULT == "skipped" ]]; then
+              exit 0
+          else
+              echo "***"
+              echo "Error: The required job did not pass."
+              exit 1
+          fi
+      - name: 'Check status of job_id: format'
+        run: |-
+          RESULT="${{ needs.format.result }}";
+          if [[ $RESULT == "success" || $RESULT == "skipped" ]]; then
+              exit 0
+          else
+              echo "***"
+              echo "Error: The required job did not pass."
+              exit 1
+          fi
+      - name: 'Check status of job_id: lint'
+        run: |-
+          RESULT="${{ needs.lint.result }}";
           if [[ $RESULT == "success" || $RESULT == "skipped" ]]; then
               exit 0
           else
